const IMAGE = {
  ICON_LOGO: require('../assets/images/logo-global.png'),
  ICON_MENU: require('../assets/images/logo-global.png'),
  ICON_USER_DEFAULT: require('../assets/images/robot-dev.png'),
  IMG_NOIMAGE: require('../assets/images/noImage.png'),
  HisPay: require('../assets/images/hisPay.png'),
  NewHis: require('../assets/images/newhistory.png'),
  Card: require('../assets/images/card3.png'),
  Password: require('../assets/images/newpassword2.png'),
  PaymentDone: require('../assets/images/Newpaid.png'),
  PhoneNo: require('../assets/images/tlp1.png'),
  Saran: require('../assets/images/saran.png'),
  List1: require('../assets/images/List1.png'),
  List2: require('../assets/images/List2.png'),
  Home: require('../assets/images/Home.png'),
  Feed: require('../assets/images/Feed.png'),
  User_Icon: require('../assets/images/user_icon.png'),
  AboutUs: require('../assets/images/about_us.png'),
  ContactUs: require('../assets/images/csNew.png'),
  ContactUs2: require('../assets/images/cs2New.png'),
  PassIcon: require('../assets/images/small_pass_visible.png'),
  HidePassIcon: require('../assets/images/small_pass_visible.png'),
  logoInsta: require('../assets/images/insta40.png'),
  logoFB: require('../assets/images/FB40.png'),
  logoTwitter: require('../assets/images/twitter50.png'),
  logoYoutube: require('../assets/images/youcir45.png'),
  noConnection: require('../assets/images/nointernet.png'),
};

export {IMAGE};
